name = "Benthos"
grammar = "yaml"
path_suffixes = ["benthos.yaml", "benthos.yml", "connect.yaml", "connect.yml"]
line_comments = ["# "]
tab_size = 2
hard_tabs = false
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
]
